version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      typescript:
        patterns:
          - "typescript*"
          - "@typescript-eslint/*"
      rollup:
        patterns:
          - "rollup*"
          - "@rollup/*"
          - "rollup-plugin-*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
      grunt:
        patterns:
          - "grunt*"
      dev:
        patterns:
          - "@nevware21/*"
          - "@microsoft/*"
  - package-ecosystem: "npm"
    directory: "/dbg"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      typescript:
        patterns:
          - "typescript*"
          - "@typescript-eslint/*"
      rollup:
        patterns:
          - "rollup*"
          - "@rollup/*"
          - "rollup-plugin-*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
      grunt:
        patterns:
          - "grunt*"
      dev:
        patterns:
          - "@nevware21/*"
          - "@microsoft/*"
  - package-ecosystem: "npm"
    directory: "/core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      rollup:
        patterns:
          - "rollup*"
          - "@rollup/*"
          - "rollup-plugin-*"
      dev:
        patterns:
          - "@nevware21/*"
          - "@microsoft/*"
